---
# tasks file for spid-testenv2
- name: make sure the directory exists
  file:
    path: "{{ spid_testenv2_dir }}"
    state: directory
    owner: "{{ spid_testenv2_user }}"
    group: "{{ spid_testenv2_user }}"
    mode: 0755

- name: install testenv2 preprequisites
  apt: pkg={{ item }} state=present update_cache=true
  with_items:
    - xmlsec1
    - libffi-dev
    - python
    - virtualenv
    - git

- name: get the spid-testenv2 repo
  git:
    repo: "https://github.com/italia/spid-testenv2.git"
    dest: "{{ spid_testenv2_dir }}"

- name: generate the IDP certificate
  command: openssl req -x509 -nodes -sha256 -days 365 -newkey rsa:2048 -subj "/C=IT/ST=Italy/L=Rome/O=testenv2/CN=${ansible_fqdn}" -keyout {{ spid_testenv2_dir }}/idp.key -out {{ spid_testenv2_dir }}/idp.crt
  args:
    creates: /etc/nginx/ssl/server.crt

- name: make sure the non-privileged user can read the key
  file:
    path: "{{ spid_testenv2_dir }}/idp.key"
    state: file
    owner: "{{ spid_testenv2_user }}"

- name: install python dependencies
  pip: requirements={{ spid_testenv2_dir }}/requirements.txt virtualenv={{ spid_testenv2_dir }}/env virtualenv_site_packages=yes

- name: Add self IP address to the hosts file
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ spid_testenv2_hostname }}"
    state: present

- name: make sure the non-privileged user can access conf dir (required to write users.json)
  file:
    path: "{{ spid_testenv2_dir }}/conf"
    state: directory
    owner: "{{ spid_testenv2_user }}"

- name: use default config
  command: cp {{ spid_testenv2_dir }}/conf/config.yaml.example {{ spid_testenv2_dir }}/conf/config.yaml

- name: install the systemd unit file
  template:
    src=testenv2.service
    dest=/etc/systemd/system/testenv2.service
    owner=root
    group=root
    mode=0644

- name: reload systemd
  command: systemctl --system daemon-reload

- name: stop testenv2 service
  command: systemctl stop testenv2

- name: configure testenv2 so that it only listens on localhost
  lineinfile:
    path: "{{ spid_testenv2_dir }}/conf/config.yaml"
    regexp: "^host:"
    line: "host: 127.0.0.1"

- name: configure the testenv2 base url
  lineinfile:
    path: "{{ spid_testenv2_dir }}/conf/config.yaml"
    regexp: "^base_url:"
    line: "base_url: https://{{ spid_testenv2_hostname }}"

- name: start testenv2 service
  command: systemctl start testenv2

- name: ensure that testenv2 is started and enabled
  service: name=testenv2
           state=started
           enabled=yes

# this final part could be delegated to an nginx role from galaxy

- name: install nginx and snakeoil certificates
  apt: pkg={{ item }} state=present update_cache=true
  with_items:
    - nginx
    - ssl-cert

- name: remove symlink to default nginx configuration
  file:
   path: "/etc/nginx/sites-enabled/default"
   state: absent

- name: install the systemd unit file
  template:
    src=myservice.conf
    dest=/etc/nginx/sites-enabled/myservice.conf
    owner=root
    group=root
    mode=0644

- name: restart nginx service
  command: systemctl restart nginx

- name: ensure that nginx is started and enabled
  service: name=nginx
           state=started
           enabled=yes
